# Data Cleaning

In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [10]:
tornados = pd.read_csv("combined_tornado_weather.csv")
pd.set_option('display.max_columns', None)
tornados.head(25)

,Unnamed: 0,om,yr,mo,dy,date,time,tz,st,stf,stn,mag,inj,fat,loss,closs,slat,slon,elat,elon,len,wid,ns,sn,sg,f1,f2,f3,f4,fc,weather_date,weather_time,wind_speed,visibility_distance,temperature,temperature_dewpoint,air_pressure,weather_date_2,weather_time_2,wind_speed_2,visibility_distance_2,temperature_2,temperature_dewpoint_2,air_pressure_2
0,1,617023,2018,12,31,2018-12-31,13:43:00,3,IN,18,0,1,0,0,50000.0,0.0,38.1813,-86.8863,38.2006,-86.8585,2.01,50,1,1,1,147,0,0,0,0,20181231,1256,46,16093,111,106,10102,20181231,1132,67,16093,100,90,99999
1,2,617024,2018,12,31,2018-12-31,14:38:00,3,IN,18,0,1,0,0,20000.0,0.0,38.0935,-86.0869,38.1000,-86.0470,2.20,140,1,1,1,61,0,0,0,0,20181231,1326,26,0,90,90,10120,20181231,1239,31,6437,80,80,10124
2,3,617013,2018,12,20,2018-12-20,07:45:00,3,FL,12,0,0,0,0,5000.0,0.0,27.7532,-81.7702,27.7424,-81.7680,0.76,75,1,1,1,105,0,0,0,0,20181220,615,9999,16093,160,9999,99999,20181220,515,9999,16093,160,9999,99999
3,4,617014,2018,12,20,2018-12-20,08:14:00,3,FL,12,0,0,1,0,45000.0,0.0,27.8287,-81.6011,27.8297,-81.6010,0.07,30,1,1,1,105,0,0,0,0,20181220,715,9999,16093,160,9999,99999,20181220,615,9999,16093,160,9999,99999
4,5,617015,2018,12,20,2018-12-20,11:28:00,3,FL,12,0,0,0,0,30000.0,0.0,27.0070,-82.1342,27.0209,-82.1286,1.02,100,1,1,1,15,0,0,0,0,20181220,1053,51,16093,194,178,10085,20181220,953,62,16093,189,172,10087
5,6,617011,2018,12,18,2018-12-18,15:50:00,3,WA,53,0,2,0,0,1180000.0,0.0,47.5070,-122.6395,47.5181,-122.6158,1.35,285,1,1,1,35,0,0,0,0,20181218,1456,57,16093,83,78,10031,20181218,1333,57,16093,80,80,99999
6,7,617010,2018,12,9,2018-12-09,10:54:00,3,FL,12,0,0,0,0,40000.0,0.0,28.5429,-81.2304,28.5447,-81.2296,0.13,50,1,1,1,95,0,0,0,0,20181209,953,46,16093,200,189,10146,20181209,815,41,16093,200,183,99999
7,8,617000,2018,12,2,2018-12-02,01:49:00,3,AL,1,0,0,0,0,15000.0,0.0,31.2374,-85.4872,31.2448,-85.4721,1.03,75,1,1,1,69,0,0,0,0,20181202,17,41,16093,194,183,99999,20181201,2323,51,8047,194,183,99999
8,9,617001,2018,12,2,2018-12-02,08:22:00,3,GA,13,0,0,0,0,10000.0,0.0,31.3390,-83.6184,31.3595,-83.5979,1.86,600,1,1,1,277,0,0,0,0,20181202,715,41,16093,9999,9999,99999,20181202,615,21,16093,9999,9999,99999
9,10,617003,2018,12,2,2018-12-02,13:30:00,3,GA,13,0,0,0,0,2000.0,0.0,31.3100,-82.8600,31.3114,-82.8573,0.19,50,1,1,1,3,0,0,0,0,20181202,1216,26,16093,220,210,99999,20181202,1116,31,8047,210,210,99999
10,11,617004,2018,12,2,2018-12-02,13:40:00,3,GA,13,0,1,0,0,0.0,0.0,31.1300,-81.5600,31.1300,-81.5500,0.59,80,1,1,1,127,0,0,0,0,20181202,1215,9999,11265,183,172,99999,20181202,1151,31,12875,180,170,99999
11,12,617005,2018,12,2,2018-12-02,14:10:00,3,GA,13,0,3,4,0,0.0,0.0,30.7800,-81.5500,30.8200,-81.4400,7.09,900,1,1,1,39,0,0,0,0,20181202,1315,9999,999999,201,9999,99999,20181202,1215,9999,999999,190,9999,99999
12,13,616959,2018,12,1,2018-12-01,00:15:00,3,MO,29,0,0,0,0,90000.0,0.0,36.8936,-93.9261,36.8939,-93.9239,0.12,50,1,1,1,9,0,0,0,0,20181130,2315,0,16093,150,130,99999,20181130,2215,0,16093,160,130,99999
13,14,616963,2018,12,1,2018-12-01,00:47:00,3,MO,29,0,1,0,0,175000.0,0.0,37.1100,-93.5300,37.1218,-93.4875,2.48,60,1,1,1,77,0,0,0,0,20181130,2349,41,12875,150,130,99999,20181130,2252,41,16093,156,122,10069
14,15,616967,2018,12,1,2018-12-01,13:47:00,3,FL,12,0,0,0,0,0.0,0.0,30.4085,-85.7476,30.4191,-85.7093,2.40,50,1,1,1,5,0,0,0,0,20181201,1253,72,14484,194,183,10112,20181201,1113,62,16093,178,161,99999
15,16,616968,2018,12,1,2018-12-01,13:54:00,3,IL,17,0,1,0,0,0.0,0.0,39.4439,-90.8510,39.4664,-90.8406,1.65,25,1,1,1,149,0,0,0,0,20181201,1215,82,16093,75,73,99999,20181201,1115,77,3219,70,69,99999
16,17,616969,2018,12,1,2018-12-01,14:29:00,3,IL,17,0,0,0,0,0.0,0.0,39.6319,-90.7143,39.6332,-90.7130,0.11,25,1,1,1,149,0,0,0,0,20181201,1315,36,16093,83,81,99999,20181201,1215,82,16093,75,73,99999
17,18,616970,2018,12,1,2018-12-01,14:34:00,3,AL,1,0,0,0,0,0.0,0.0,32.5290,-87.3640,32.5294,-87.3588,0.30,75,1,1,1,105,0,0,0,0,20181201,1315,9999,999999,150,9999,99999,20181201,1215,9999,999999,153,9999,99999
18,19,616971,2018,12,1,2018-12-01,14:40:00,3,IL,17,0,1,0,0,0.0,0.0,39.7272,-90.6537,39.7186,-90.6555,0.60,110,1,1,1,149,0,0,0,0,20181201,1315,36,16093,83,81,99999,20181201,1215,82,16093,75,73,99999
19,20,616974,2018,12,1,2018-12-01,15:09:00,3,IL,17,0,0,0,0,35000.0,0.0,39.9115,-90.4667,39.9191,-90.4599,0.64,50,1,1,1,17,0,0,0,0,20181201,1415,67,16093,100,96,99999,20181201,1315,82,16093,82,78,99999
20,21,616975,2018,12,1,2018-12-01,15:18:00,3,IL,17,0,0,0,0,0.0,0.0,40.3600,-90.6500,40.3600,-90.6500,0.10,15,1,1,1,109,0,0,0,0,20181201,1420,67,16093,21,20,99999,20181201,1315,124,16093,20,17,99999
21,22,616977,2018,12,1,2018-12-01,15:41:00,3,IL,17,0,0,0,0,0.0,0.0,40.4800,-90.5900,40.4800,-90.5900,0.10,15,1,1,1,109,0,0,0,0,20181201,1420,67,16093,21,20,99999,20181201,1315,124,16093,20,17,99999
22,23,616981,2018,12,1,2018-12-01,15:59:00,3,IL,17,0,1,0,0,0.0,0.0,39.0310,-89.7523,39.0465,-89.7359,1.39,50,1,1,1,117,0,0,0,0,20181201,1415,51,16093,124,120,99999,20181201,1315,72,16093,111,110,99999
23,24,616982,2018,12,1,2018-12-01,16:09:00,3,IL,17,0,1,0,0,0.0,0.0,39.2315,-89.6819,39.3352,-89.6143,8.03,75,1,1,1,135,0,0,0,0,20181201,1515,62,16093,136,121,99999,20181201,1415,51,16093,124,120,99999
24,25,616983,2018,12,1,2018-12-01,16:16:00,3,IL,17,0,2,0,0,0.0,0.0,39.1522,-89.6324,39.2361,-89.5663,6.79,100,1,1,1,135,0,0,0,0,20181201,1515,62,16093,136,121,99999,20181201,1415,51,16093,124,120,99999

Get the number of tornados by class

In [3]:
tornados['mag'].value_counts()

 0    2585
 1    1774
 2     449
 3     113
-9      45
 4      30
 5       4
Name: mag, dtype: int64

Replace coded na's with actual na's

In [4]:
replace_map3 = {'mag': {-9: np.nan},
                'visibility_distance':{999999: np.nan},
                'wind_speed':{9999: np.nan},
                'temperature':{9999:np.nan},
                'temperature_dewpoint': {9999:np.nan },
                'air_pressure': {99999: np.nan},
                'visibility_distance_2':{999999: np.nan},
                'wind_speed_2':{9999: np.nan},
                'temperature_2':{9999:np.nan},
                'temperature_dewpoint_2': {9999:np.nan },
                'air_pressure_2': {99999: np.nan}
               }

tornados_clean = tornados.replace(replace_map3)
# Remove unlabeled tornados
tornados_clean = tornados_clean.dropna(subset=['mag'])

In [9]:
tornados_clean.head(10)

,Unnamed: 0,om,yr,mo,dy,date,time,tz,st,stf,stn,mag,inj,fat,loss,closs,slat,slon,elat,elon,len,wid,ns,sn,sg,f1,f2,f3,f4,fc,weather_date,weather_time,wind_speed,visibility_distance,temperature,temperature_dewpoint,air_pressure,weather_date_2,weather_time_2,wind_speed_2,visibility_distance_2,temperature_2,temperature_dewpoint_2,air_pressure_2,time_binned
0,1,617023,2018,12,31,2018-12-31,13:43:00,3,IN,18,0,1.0,0.0,0.0,50000.0,0.0,38.1813,-86.8863,38.2006,-86.8585,2.01,50.0,1,1,1,147,0,0,0,0,20181231,1256,46.0,16093.0,111.0,106.0,10102.0,20181231,1132,67.0,16093.0,100.0,90.0,10088.4,4
1,2,617024,2018,12,31,2018-12-31,14:38:00,3,IN,18,0,1.0,0.0,0.0,20000.0,0.0,38.0935,-86.0869,38.1000,-86.0470,2.20,140.0,1,1,1,61,0,0,0,0,20181231,1326,26.0,0.0,90.0,90.0,10120.0,20181231,1239,31.0,6437.0,80.0,80.0,10124.0,4
2,3,617013,2018,12,20,2018-12-20,07:45:00,3,FL,12,0,0.0,0.0,0.0,5000.0,0.0,27.7532,-81.7702,27.7424,-81.7680,0.76,75.0,1,1,1,105,0,0,0,0,20181220,615,80.0,16093.0,160.0,154.0,10090.8,20181220,515,68.6,16093.0,160.0,147.4,10094.4,2
3,4,617014,2018,12,20,2018-12-20,08:14:00,3,FL,12,0,0.0,1.0,0.0,45000.0,0.0,27.8287,-81.6011,27.8297,-81.6010,0.07,30.0,1,1,1,105,0,0,0,0,20181220,715,54.4,16093.0,160.0,136.4,10101.0,20181220,615,34.8,16093.0,160.0,134.4,10094.6,2
4,5,617015,2018,12,20,2018-12-20,11:28:00,3,FL,12,0,0.0,0.0,0.0,30000.0,0.0,27.0070,-82.1342,27.0209,-82.1286,1.02,100.0,1,1,1,15,0,0,0,0,20181220,1053,51.0,16093.0,194.0,178.0,10085.0,20181220,953,62.0,16093.0,189.0,172.0,10087.0,3
5,6,617011,2018,12,18,2018-12-18,15:50:00,3,WA,53,0,2.0,0.0,0.0,1180000.0,0.0,47.5070,-122.6395,47.5181,-122.6158,1.35,285.0,1,1,1,35,0,0,0,0,20181218,1456,57.0,16093.0,83.0,78.0,10031.0,20181218,1333,57.0,16093.0,80.0,80.0,10089.6,4
6,7,617010,2018,12,9,2018-12-09,10:54:00,3,FL,12,0,0.0,0.0,0.0,40000.0,0.0,28.5429,-81.2304,28.5447,-81.2296,0.13,50.0,1,1,1,95,0,0,0,0,20181209,953,46.0,16093.0,200.0,189.0,10146.0,20181209,815,41.0,16093.0,200.0,183.0,10106.6,3
7,8,617000,2018,12,2,2018-12-02,01:49:00,3,AL,1,0,0.0,0.0,0.0,15000.0,0.0,31.2374,-85.4872,31.2448,-85.4721,1.03,75.0,1,1,1,69,0,0,0,0,20181202,17,41.0,16093.0,194.0,183.0,10138.4,20181201,2323,51.0,8047.0,194.0,183.0,10133.8,1
8,9,617001,2018,12,2,2018-12-02,08:22:00,3,GA,13,0,0.0,0.0,0.0,10000.0,0.0,31.3390,-83.6184,31.3595,-83.5979,1.86,600.0,1,1,1,277,0,0,0,0,20181202,715,41.0,16093.0,238.2,185.4,10093.4,20181202,615,21.0,16093.0,232.0,186.0,10136.0,2
9,10,617003,2018,12,2,2018-12-02,13:30:00,3,GA,13,0,0.0,0.0,0.0,2000.0,0.0,31.3100,-82.8600,31.3114,-82.8573,0.19,50.0,1,1,1,3,0,0,0,0,20181202,1216,26.0,16093.0,220.0,210.0,10036.2,20181202,1116,31.0,8047.0,210.0,210.0,10099.0,4

Bin the time of touchdown of the tornado into 6 bins

In [6]:
hours = pd.to_datetime(tornados['time'], format='%H:%M:%S').dt.hour
tornados_clean['time_binned'] = pd.cut(hours, 
                    bins=[0,4,8,12, 16, 20, 24], 
                    include_lowest=True, 
                    labels=['1','2','3','4','5','6'])
tornados_clean.head()

,Unnamed: 0,om,yr,mo,dy,date,time,tz,st,stf,stn,mag,inj,fat,loss,closs,slat,slon,elat,elon,len,wid,ns,sn,sg,f1,f2,f3,f4,fc,weather_date,weather_time,wind_speed,visibility_distance,temperature,temperature_dewpoint,air_pressure,weather_date_2,weather_time_2,wind_speed_2,visibility_distance_2,temperature_2,temperature_dewpoint_2,air_pressure_2,time_binned
0,1,617023,2018,12,31,2018-12-31,13:43:00,3,IN,18,0,1.0,0,0,50000.0,0.0,38.1813,-86.8863,38.2006,-86.8585,2.01,50,1,1,1,147,0,0,0,0,20181231,1256,46.0,16093.0,111.0,106.0,10102.0,20181231,1132,67.0,16093.0,100.0,90.0,NaN,4
1,2,617024,2018,12,31,2018-12-31,14:38:00,3,IN,18,0,1.0,0,0,20000.0,0.0,38.0935,-86.0869,38.1000,-86.0470,2.20,140,1,1,1,61,0,0,0,0,20181231,1326,26.0,0.0,90.0,90.0,10120.0,20181231,1239,31.0,6437.0,80.0,80.0,10124.0,4
2,3,617013,2018,12,20,2018-12-20,07:45:00,3,FL,12,0,0.0,0,0,5000.0,0.0,27.7532,-81.7702,27.7424,-81.7680,0.76,75,1,1,1,105,0,0,0,0,20181220,615,NaN,16093.0,160.0,NaN,NaN,20181220,515,NaN,16093.0,160.0,NaN,NaN,2
3,4,617014,2018,12,20,2018-12-20,08:14:00,3,FL,12,0,0.0,1,0,45000.0,0.0,27.8287,-81.6011,27.8297,-81.6010,0.07,30,1,1,1,105,0,0,0,0,20181220,715,NaN,16093.0,160.0,NaN,NaN,20181220,615,NaN,16093.0,160.0,NaN,NaN,2
4,5,617015,2018,12,20,2018-12-20,11:28:00,3,FL,12,0,0.0,0,0,30000.0,0.0,27.0070,-82.1342,27.0209,-82.1286,1.02,100,1,1,1,15,0,0,0,0,20181220,1053,51.0,16093.0,194.0,178.0,10085.0,20181220,953,62.0,16093.0,189.0,172.0,10087.0,3

Impute missing values and convert numeric values to floats

In [7]:
# Numeric predictors
numeric_predictors = ['inj', 'fat', 'loss', 'closs', 'slat', 'slon', 'elat', 'elon', 'len', 'wid', 'wind_speed','visibility_distance','temperature','temperature_dewpoint','air_pressure','wind_speed_2','visibility_distance_2','temperature_2','temperature_dewpoint_2','air_pressure_2']
tornados_clean[numeric_predictors] = tornados_clean[numeric_predictors].astype(float)

# Use knn to impute all missing values
from sklearn.impute import KNNImputer
imputer = KNNImputer(n_neighbors=5, weights="uniform")
tornados_clean[numeric_predictors] = imputer.fit_transform(tornados_clean[numeric_predictors])

In [8]:
# Write out cleaned data to csv
tornados_clean.to_csv('combined_tornado_weather_clean.csv', index=False)

Generate a training and test set

In [180]:
n = tornados_clean.shape[0]
# Numeric, categorical predictors and response, y`
x_num = tornados_clean[numeric_predictors]
x_cat = tornados_clean[['st','time_binned']]
y = tornados_clean['mag']
all_predictors = numeric_predictors
# No. of predictors
k = len(all_predictors)
# Standardize numeric columns, to mean 0 variance 1
mean = x_num.mean()
std = x_num.std()
x_num = np.array((x_num - mean) / std)
# Put them into one data matrix
X = pd.DataFrame(np.concatenate((x_num, x_cat), axis = 1), columns = numeric_predictors + ['st', 'time_binned'])
X[numeric_predictors] = X[numeric_predictors].astype(float)
display(X.describe())

inj                       float64
fat                       float64
loss                      float64
closs                     float64
slat                      float64
slon                      float64
elat                      float64
elon                      float64
len                       float64
wid                       float64
wind_speed                float64
visibility_distance       float64
temperature               float64
temperature_dewpoint      float64
air_pressure              float64
wind_speed_2              float64
visibility_distance_2     float64
temperature_2             float64
temperature_dewpoint_2    float64
air_pressure_2            float64
st                         object
time_binned                object
dtype: object

,inj,fat,loss,closs,slat,slon,elat,elon,len,wid,wind_speed,visibility_distance,temperature,temperature_dewpoint,air_pressure,wind_speed_2,visibility_distance_2,temperature_2,temperature_dewpoint_2,air_pressure_2
count,9.760000e+02,9.760000e+02,9.760000e+02,9.760000e+02,9.760000e+02,9.760000e+02,9.760000e+02,9.760000e+02,9.760000e+02,9.760000e+02,9.760000e+02,9.760000e+02,9.760000e+02,9.760000e+02,9.760000e+02,9.760000e+02,9.760000e+02,9.760000e+02,9.760000e+02,9.760000e+02
mean,2.020526e-16,-3.345457e-16,1.642300e-16,1.335453e-16,-1.084367e-14,2.645709e-15,4.489862e-15,1.271763e-14,-1.435953e-15,-1.002158e-16,-2.845515e-16,1.475709e-15,4.980078e-16,5.517558e-16,2.418112e-13,1.641447e-16,1.261286e-15,-5.678518e-16,-7.848060e-16,4.203391e-13
std,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00
min,-1.160494e-01,-6.411716e-02,-8.524026e-02,-6.645013e-02,-2.470093e+00,-3.937480e+00,-2.474872e+00,-3.942190e+00,-6.628981e-01,-6.929989e-01,-1.702458e+00,-3.562684e+00,-4.424294e+00,-6.753962e+00,-4.764819e+00,-1.640861e+00,-3.479432e+00,-3.854947e+00,-6.559433e+00,-4.569305e+00
25%,-1.160494e-01,-6.411716e-02,-8.524026e-02,-6.645013e-02,-7.371987e-01,-6.100674e-01,-7.418452e-01,-6.070865e-01,-5.745395e-01,-4.947343e-01,-7.302512e-01,9.160269e-02,-5.446733e-01,-4.548064e-01,-5.658374e-01,-6.779564e-01,1.117838e-01,-6.054009e-01,-4.239465e-01,-5.488386e-01
50%,-1.160494e-01,-6.411716e-02,-8.501414e-02,-6.645013e-02,3.216375e-02,-4.212877e-02,3.236024e-02,-4.459169e-02,-3.390927e-01,-3.614377e-01,-1.693624e-01,4.975505e-01,5.666791e-02,1.796409e-01,-1.307298e-02,-1.224348e-01,5.107251e-01,8.681007e-02,9.677746e-02,4.210283e-02
75%,-1.160494e-01,-6.411716e-02,-7.958724e-02,-6.645013e-02,7.531645e-01,7.471476e-01,7.532574e-01,7.450499e-01,1.836519e-01,1.986319e-01,6.158820e-01,4.975505e-01,6.386110e-01,6.554764e-01,6.106888e-01,6.552954e-01,5.107251e-01,6.251964e-01,7.080621e-01,6.330443e-01
max,1.645920e+01,1.558047e+01,2.252683e+01,2.714824e+01,2.116907e+00,2.482710e+00,2.114581e+00,2.482018e+00,7.529590e+00,9.047732e+00,4.056000e+00,4.975505e-01,3.005180e+00,2.241595e+00,2.968812e+00,4.062495e+00,5.107251e-01,2.874882e+00,2.247594e+00,2.888428e+00

In [181]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.10, random_state=42)